FROM node:20.13.1

WORKDIR /usr/src/app

# Copie o package.json e o package-lock.json
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código da aplicação
COPY . .

# Exponha a porta que o aplicativo irá rodar
EXPOSE 3000

# Comando para rodar o aplicativo
CMD [ "node", "src/server.js" ]