name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4.18
        container_name: comp-db
        #restart: unless-stopped
        ports:
          - "28017:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: "root"
          MONGO_INITDB_ROOT_PASSWORD: "root"
          MONGO_INITDB_DATABASE: library
        volumes:
          - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
          - .volumes/database/mongodb:/data/db
        tty: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
